### ISSUE TITLE
Todo-list for 1.0.0

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/river_pod#531]
- [ ] ~~ref.read should maintain the state of auto-dispose providers~~ cancelled 
- [ ] ~~release the Flutter Devtool screen for Riverpod~~ will be completed after the 1.0 release
- [ ] ~~#779~~ will be added in version 1.1
- [ ] ~~add a way to debounce/throttle async providers~~ will be added in version 1.1
- [ ] ~~add a way to use `select` in combination with `ref.watch(provider.future/last)` that can be awaited~~ will be added in version 1.1
- [x] Allow all providers that emits an `AsyncValue` do to `ref.watch(provider.future)`/`ref.watch(provider.stream)`
- [x] refactor FutureProviderElement & co to proper classes instead of typedefs.
- [x] add `ref.state` and `ref.state =` for providers
- [x] revamp error handling
- [x] have ref.listen receive the previous value, if any
- [x] Update Consumer/ConsumerWidget
- [x] Remove useProvider in favor of HookConsumerWidget
- [x] Add HookConsumer/HookConsumerWidget
- [x] update all docs
- [x] implement ref.listen
- [x] implement ref.read/refresh (and deprecate context variants)
- [x] support ref.watch(provider.select) inside providers
- [x] support ref.watch(provider.select) inside widgets
- [x] remove ScopedProvider and allow all providers to be scoped.
- [x] pass the previous value to ProviderObserver.didUpdateProvider.
- [x] fixes https://github.com/rrousselGit/river_pod/issues/358
- [x] remove AsyncValue.copyWith
- [x] add a StateController.update((state) => newState);
- [x] add tons of tests
- [x] add "dependencies" to auto-scope providers if a dependency is overriden
- [x] remove overrideWithProvider
- [x] have StateNotifier/StateController filter state with == https://github.com/rrousselGit/river_pod/issues/133

**Comment by rrousselGit** [comment]
If you see anything missing / you think should be covered, don't hesitate to leave a message

**Comment by gabrielvictorjs** [comment]
I really miss `MultiProviderListener` :(

**Comment by rrousselGit** [comment]
It is there:

```dart
Consumer(
  builder: (context, ref, child) {
    ref.listen<Model>(provider, (model) {
      print('model changed $model');
    });
  },
)
```

**Comment by gabrielvictorjs** [comment]
Nice. So, all that's left is to update the docs. Thanks!

**Comment by creativecreatorormaybenot** [comment]
Looking at #532, I guess that one is missing.

**Comment by TimWhiting** [comment]
Are you planning to add StreamProvider.future and deprecate .last to unify the async APIs?

**Comment by rrousselGit** [comment]
@TimWhiting I don't think so. The benefits are low

**Comment by tim-smart** [comment]
"Remove useProvider in favor of HookConsumerWidget" feels like a step backwards in my opinion.

Breaks the "everything is a hook" approach.
